version: "3.9"
services:
  app:
    build: ./FlaskApp
    ports:
      - "5000:5000"
    links:
      - "db"
    environment:
      MYSQL_DATABASE_DB: BucketList
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_HOST: db
  db:
    build: ./MYSQL_Queries
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    